name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node V20.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci
        env:
          CI: true

      - name: Build Package
        run: npm run generate-module

      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
